### ISSUE TITLE
Issues with running Deno

### ISSUE THREAD

**Issue by sacha-l** [kodadot/fandom#19]
I'm not exactly sure what the source of the issue could be, but when I run `deno task start` I get:

```bash
An error occurred during route handling or page rendering. TypeError: Cannot read properties of null (reading 'useSyncExternalStore')
    at n.useSyncExternalStore (https://esm.sh/stable/react@18.2.0/X-ZS9wcmVhY3QvY29tcGF0/deno/react.mjs:2:6960)
    at Pe (https://esm.sh/v98/swr@2.0.0-beta.6/X-YS9yZWFjdDpwcmVhY3QvY29tcGF0CmUvcHJlYWN0L2NvbXBhdA/deno/swr.mjs:2:3511)
    at https://esm.sh/v98/swr@2.0.0-beta.6/X-YS9yZWFjdDpwcmVhY3QvY29tcGF0CmUvcHJlYWN0L2NvbXBhdA/deno/_internal.js:2:8091
    at https://esm.sh/v98/swr@2.0.0-beta.6/X-YS9yZWFjdDpwcmVhY3QvY29tcGF0CmUvcHJlYWN0L2NvbXBhdA/deno/_internal.js:2:8335
    at useStargazers (file:///Users/sachalansky/Documents/GitHub/Workshops-2023%F0%9F%8C%88/fandom/utils/data.ts:15:10)
    at Object.StarGazers (file:///Users/sachalansky/Documents/GitHub/Workshops-2023%F0%9F%8C%88/fandom/islands/StarGazers.tsx:7:27)
    at https://esm.sh/v98/preact-render-to-string@5.2.3/X-ZS8q/deno/preact-render-to-string.mjs:12:1590
    at T (https://esm.sh/v98/preact-render-to-string@5.2.3/X-ZS8q/deno/preact-render-to-string.mjs:12:1617)
    at T (https://esm.sh/v98/preact-render-to-string@5.2.3/X-ZS8q/deno/preact-render-to-string.mjs:12:2593)
    at T (https://esm.sh/v98/preact-render-to-string@5.2.3/X-ZS8q/deno/preact-render-to-string.mjs:12:1693)
 ```

What I think it could be is that it's related to something broken on the React JSX side. 

<img width="1161" alt="Screenshot 2023-04-28 at 1 12 57 PM" src="https://user-images.githubusercontent.com/23283108/235135422-529eed0b-84b1-4644-90b5-9fcad7afaad9.png">

**Comment by vikiival** [comment]
Hello,
thanks for opening the issue!


Which version do you use please?
```
$ deno --version
deno 1.32.5 (release, aarch64-apple-darwin)
v8 11.2.214.9
typescript 5.0.3
```

I pushed also latest lock in 28113dcfa09a7e5075a77b9538a2821edbcb818f

**Comment by sacha-l** [comment]
My Deno version is also:

```
deno 1.32.5 (release, aarch64-apple-darwin)
v8 11.2.214.9
typescript 5.0.3
```

**Comment by vikiival** [comment]
Hello @sacha-l,

I finally found the root issue of this error.

Seems that `swr` package I was using for fetching stargazers seems to be leaky with Preact

<img width="988" alt="Screenshot 2023-04-30 at 21 18 42" src="https://user-images.githubusercontent.com/22471030/235372253-4042006d-2a1d-44e6-b65e-d806c4301c33.png">


please pull the latest main ❤️
